[general]
    description = "Juliet tests"
    execCmd = "./pmd-bin-6.40.0/bin/run.sh pmd -R category/java/security.xml -f text -d"
    expectedWarningsPattern = "/\\* (FLAW|POTENTIAL\\sFLAW|FIX):(\\d*)? (.+)"
    expectedWarningsMiddlePattern = "\\* (.*)"
    expectedWarningsEndPattern = "(.*)?\\*/"
    timeOutMillis = 30000

[warn]
    testNameRegex = "CWE.*java"
    actualWarningsPattern = "(\\w+\\.java):(\\d+):\\s+(.*)$"
    lineCaptureGroup = 2
    messageCaptureGroup = 3
    fileNameCaptureGroupOut = 1
    lineCaptureGroupOut = 2
    messageCaptureGroupOut = 3
    warningTextHasLine = true
    warningTextHasColumn = false
    exactWarningsMatch = true
    benchmarkMode = true
